import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { PostHogProvider } from "./providers";
import { ThemeProvider } from "@/contexts/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://"),
  title: { default: " | ", template: "%s | " },
  description: "Generated by create next app",
  applicationName: "",
  authors: [{ name: "" }],
  generator: "Nextjs",
  referrer: "origin-when-cross-origin",
  keywords: [],
  creator: "",
  publisher: "",
  formatDetection: { email: false, address: false, telephone: false },
  icons: { icon: [{ url: "", type: "image/" }], apple: "", shortcut: "" },
  manifest: "/site.webmanifest",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://",
    siteName: "",
    title: "",
    description: "",
    images: [{ url: "", width: 1200, height: 630, alt: "" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "",
    description: "",
    images: [""],
    creator: "",
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  category: "",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <PostHogProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </PostHogProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
